# -*- coding: utf-8 -*-
"""samplesuperstore.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uU_VJJwtcGOMbDxEDNmzYm4KbpBwpV6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from scipy import stats

path = "/content/samplesuperstore - samplesuperstore.csv"
df = pd.read_csv(path)

from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

print(df.head())

print(df.info())

print(df.describe())

print(df.isnull().sum())

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df["Category"] = df["Category"].str.strip().str.title()
df["Sub-Category"] = df["Sub-Category"].str.strip().str.title()
df["Segment"] = df["Segment"].str.strip().str.title()

print(df[["Sales", "Profit", "Quantity", "Discount"]].describe())

print("Average Sales:", np.mean(df["Sales"]))

sales = df.groupby("Category")["Sales"].sum()
print(sales)

plt.figure(figsize=(6,4))
plt.bar(sales.index, sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(data=df, x="Sales", y="Profit")
plt.title("Sales vs Profit")
plt.show()

X_train, X_test = train_test_split(df, test_size=0.2, random_state=42)

print("Training Rows:", len(X_train))
print("Testing Rows:", len(X_test))

print("Mean Sales:", stats.tmean(df["Sales"]))