# -*- coding: utf-8 -*-
"""STUDENT ANALYSIS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfnvDrp1ByOSHKH-N2I6kvMvYqNEnnP0
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("studentperformance preprocessed.csv")
scores = ["math score", "reading score", "writing score"]

df.groupby("parental level of education")[scores].mean().plot(kind="bar")
plt.title("Scores by Parental Education")
plt.show()

df.groupby("lunch")[scores].mean().plot(kind="bar")
plt.title("Scores by Lunch Type")
plt.show()

long = df.melt(id_vars="test preparation course", value_vars=scores,
               var_name="subject", value_name="score")
sns.boxplot(data=long, x="subject", y="score", hue="test preparation course")
plt.show()

sns.pairplot(df[scores])
plt.show()

sns.heatmap(df[scores].corr(), annot=True, cmap="coolwarm")
plt.show()